import test from 'node:test';import assert from 'node:assert/strict';
import{seedState,balances,purchase,quote,redeem,metrics,groups,categories}from'../assets/demo-model.mjs';
const turn={branch:'Playas',actorId:'ana',customerId:'DEMO-ANA',day:'2026-10-09',hour:16};
test('seed data is rich, has five ranked categories and no prices or contacts',()=>{const s=seedState('2026-10-09'),d=metrics(s,30,'all','2026-10-09');assert.equal(s.customers.length,120);assert.ok(d.tickets.length>150);assert.ok(d.active>60);assert.ok(d.totals.every(p=>p.units>0));assert.deepEqual(categories.map(c=>c.name),['Americano','Clásicos','Temporada','Alimentos','Postres']);assert.ok(d.totals.every((p,i,a)=>!i||a[i-1].units>=p.units));assert.equal(d.totals.reduce((n,p)=>n+p.units,0),d.tickets.reduce((n,e)=>n+e.quantities.reduce((a,b)=>a+b,0),0));assert.ok(!JSON.stringify(s).includes('email'));assert.ok(!JSON.stringify(s).includes('price'));assert.ok(s.events.every(e=>s.team.some(t=>t.id===e.actorId&&t.branches.includes(e.branch))));assert.ok(s.customers.every(c=>{const b=balances(s,c.id);return b.grains>=0&&b.stamps>=0;}));});
test('category units earn Granos once and never change stamps',()=>{const s=seedState('2026-10-09'),before=balances(s,turn.customerId),command={...turn,id:'one',quantities:[1,2,1,1,1]};const e=purchase(s,command);assert.equal(e.earned,51);purchase(s,command);const after=balances(s,turn.customerId);assert.equal(after.grains-before.grains,51);assert.equal(after.stamps,before.stamps);assert.equal(s.events.filter(e=>e.id==='one').length,1);});
test('switching modes preserves both balances; only beverages earn stamps',()=>{const s=seedState('2026-10-09'),before=balances(s,turn.customerId);s.mode='stamps';purchase(s,{...turn,id:'stamps',quantities:[1,2,1,4,3]});s.mode='grains';assert.deepEqual(balances(s,turn.customerId),{grains:before.grains,stamps:before.stamps+4});});
test('completed cards keep accumulating; redemption consumes one reward and preserves next progress',()=>{const s=seedState('2026-10-09');s.mode='stamps';assert.equal(balances(s,turn.customerId).stamps,18);purchase(s,{...turn,id:'extra',quantities:[1,0,0,0,0]});const command={...turn,id:'redeem',mode:'stamps'};redeem(s,command);redeem(s,command);assert.equal(balances(s,turn.customerId).stamps,11);assert.equal(Math.floor(11/s.target),1);assert.equal(11%s.target,3);});
test('invalid quantities, unauthorized branch and insufficient balance are rejected',()=>{const s=seedState('2026-10-09');for(const quantities of [[-1,0,0,0,0],[51,0,0,0,0],[.5,0,0,0,0],[0,0,0,0,0],[1]])assert.throws(()=>purchase(s,{...turn,id:crypto.randomUUID(),quantities}));assert.throws(()=>purchase(s,{...turn,id:'bad-turn',actorId:'diego',branch:'Cacho',quantities:[1,0,0,0,0]}));s.customers.push({id:'empty',openingGrains:0,openingStamps:0});assert.throws(()=>redeem(s,{...turn,id:'empty-reward',customerId:'empty',rewardId:'americano'}));});
test('reports respect periods, branches and small demographic groups',()=>{const s=seedState('2026-10-09'),all=metrics(s,30,'all','2026-10-09'),p=metrics(s,30,'Playas','2026-10-09'),c=metrics(s,30,'Cacho','2026-10-09');assert.equal(all.tickets.length,p.tickets.length+c.tickets.length);assert.equal(all.average,all.tickets.length/all.active);assert.ok(groups(s,all.tickets,'ageBand').every(g=>g.customers>=5));assert.equal(groups(s,[all.tickets[0]],'gender').length,0);assert.ok(metrics(s,7,'all','2026-10-09').tickets.length<=all.tickets.length);});
test('experimental schedule has an exclusive end and never affects stamps',()=>{const s=seedState('2026-10-09');s.lab.happy=true;const e=purchase(s,{...turn,id:'happy',hour:15,quantities:[1,0,0,0,0]});assert.equal(e.earned,10);assert.equal(purchase(s,{...turn,id:'end',hour:18,quantities:[1,0,0,0,0]}).earned,5);s.mode='stamps';assert.equal(purchase(s,{...turn,id:'stamp',hour:16,quantities:[1,0,0,0,0]}).earned,1);});

test('preview and capture use the same experimental reward calculation',()=>{const s=seedState('2026-10-09');s.lab.happy=true;s.lab.combo=true;const command={...turn,id:'preview',quantities:[1,0,0,1,0]};const before=s.events.length;const preview=quote(s,command);assert.equal(s.events.length,before);assert.equal(purchase(s,command).earned,preview);assert.equal(preview,42);});
